FROM <%= c['docker.repository'] %>/kalibro

MAINTAINER <%= c['docker.maintainer'] %>

<% if c['phantomjs.install'] %>
<%= import["Dockerfile-phantomjs.erb"] %>
<% end %>

<%= apt.update %>
<%= apt.install('curl libpq-dev', recommends: false, suggests: false) %>

RUN curl -L https://get.rvm.io | bash
RUN bash -l -c 'rvm requirements'
RUN echo 'gem: --no-document' > /root/.gemrc
 
<%= import["Dockerfile-gatekeeper.erb"] %>

<% if c['mezuro.install'] %>
<%= import["Dockerfile-mezuro.erb"] %>
<% end %>

<%= docker.ports %>