ADD mezuro_checkout.sh /home/mezuro/
RUN sudo -u mezuro -- /home/mezuro/mezuro_checkout.sh
RUN sudo -u mezuro -- sh -c 'cd /home/mezuro/mezuro; rvm install $(cat .ruby-version)'
RUN sudo -u mezuro -- sh -c 'cd /home/mezuro/mezuro; gem install bundler && bundle install -j4'

<%= docker.copy_tmpl('mezuro_setup.sh.erb',
                     '/home/mezuro/mezuro_setup.sh') %>
<%= docker.copy_tmpl('mezuro_start.sh.erb',
                     '/home/mezuro/mezuro_start.sh') %>
