FROM <%= c['docker.repository'] %>/base

MAINTAINER <%= c['docker.maintainer'] %>

<%= Apt::install('curl libpq-dev', recommends: false, suggests: false) %>

RUN curl -L https://get.rvm.io | bash
RUN bash -l -c "rvm requirements"
RUN echo "gem: --no-document" > /root/.gemrc

<%= import["Dockerfile-kalibro.erb"] %>

<%= import["Dockerfile-gatekeeper.erb"] %>

<%= import["Dockerfile-mezuro.erb"] %>

<%= import["../base/Dockerfile-ports.erb"] %>