ADD <%= c['phantomjs.download_path'] %> /var/tmp/phantomjs.tar.bz2

RUN mkdir -p '<%= c['phantomjs.install_path'] %>' \
 && chmod 775 '<%= c['phantomjs.install_path'] %>'
RUN tar xf /var/tmp/phantomjs.tar.bz2 -C '<%= c['phantomjs.install_path'] %>' \
 --no-same-owner
RUN ln -s '<%= c['phantomjs.install_path'] %>/bin/phantomjs' /usr/local/bin/phantomjs