<%= git.import_or_clone(c['mezuro.install_path'],
                         'https://github.com/mezuro/mezuro.git') %>

RUN bash -l -c 'cd <%= c['mezuro.install_path'] %> && rvm install ./.ruby-version'
RUN bash -l -c 'cd <%= c['mezuro.install_path'] %> && gem install bundler && bundle install -j4'

<%= docker.copy_tmpl('mezuro_setup.sh.erb', File.join(c['mezuro.install_path'], 'setup.sh')) %>

<%= docker.copy_tmpl('mezuro_start.sh.erb', File.join(c['mezuro.install_path'], 'start.sh')) %>
