RUN wget 'http://phantomjs.googlecode.com/files/phantomjs-<%= c['phantomjs.version'] %>-linux-x86_64.tar.bz2' -O /root/phantomjs.tar.bz2'

RUN mkdir -p '<%= c['phantomjs.install_path'] %>'
RUN tar xjf /root/phantomjs.tar.bz2 -C '<%= c['phantomjs.install_path'] %>'
RUN ln -s '<%= c['phantomjs.install_path'] %>/bin/phantomjs' /usr/local/bin/phantomjs