FROM ubuntu:<%= c['ubuntu.version'] %>

MAINTAINER <%= c['docker.maintainer'] %>

ENV LANG en_US.UTF-8
RUN locale-gen en_US.UTF-8

RUN sed -i /etc/apt/sources.list \
 -e 's#http://archive\.ubuntu\.com/ubuntu#''<%= c['ubuntu.mirror'] %>''#'

<% if c['apt.use_proxy'] %>
<%= docker.copy_tmpl('apt-proxy.conf.erb', '/etc/apt/conf.d/02-proxy.conf') %> 
<% end %>

<%= apt.update %>
<%= apt.install('apt-utils ca-certificates wget unzip git-core',
                 recommends: false, suggests: false) %>

<%= apt.install('openssh-server', recommends: false, suggests: false) %>
<%= apt.reconfigure('openssh-server') %>

<%= docker.ports %>