FROM <%= c['docker.repository'] %>/base

MAINTAINER <%= c['docker.maintainer'] %>

<%= import["Dockerfile-gatekeeper.erb"] %>
 
<% if c['ssh.expose'] %>
EXPOSE 22:<%= c['ssh.dest_port'] %>
<% end %>

CMD /bin/init