FROM <%= c['docker.repository'] %>/base

MAINTAINER <%= c['docker.maintainer'] %>

<%= Apt::install('curl', recommends: false, suggests: false) %>

RUN curl -L https://get.rvm.io | bash
RUN /bin/bash -l -c "rvm requirements"
RUN echo "gem: --no-ri --no-rdoc" > /root/.gemrc

<%= import["Dockerfile-kalibro.erb"] %>
<%= import["Dockerfile-gatekeeper.erb"] %>
<%= import["Dockerfile-mezuro.erb"] %>

<%= import["../base/Dockerfile-ports.erb"] %>

CMD /bin/init
