RUN useradd kalibro_gatekeeper -d /home/mezuro/kalibro_gatekeeper

ADD gemrc /home/mezuro/kalibro_gatekeeper/.gemrc

RUN su kalibro_gatekeeper -c 'curl -L https://get.rvm.io | bash -s stable'
RUN su kalibro_gatekeeper -l -c "rvm requirements"
RUN su kalibro_gatekeeper -l -c "rvm install <%= c['kalibro_gatekeeper.ruby_version'] %>"
RUN su kalibro_gatekeeper -l -c "gem install bundler"
RUN su kalibro_gatekeeper -l -c "bundle install"