<%= Apt::install('postgresql') %>

<%= Apt::install('libpostgresql-jdbc-java tomcat6',
                 recommends: false, suggests: false) %> 

ADD analizo.list /etc/apt/sources.list.d/analizo.list
ADD analizo.preferences /etc/apt/preferences.d/analizo
RUN wget -O - http://analizo.org/download/signing-key.asc | apt-key add -

<%= Apt::update %>

<%= Apt::install('analizo', recommends: false, suggests: false) %>

RUN mkdir -p /usr/share/tomcat6/.kalibro/projects \ 
 /usr/share/tomcat6/.kalibro/logs \
 && chown -R :tomcat6 /usr/share/tomcat6/.kalibro \
 && chmod 'g+s,a+r,ug+w,o-w' -R /usr/share/tomcat6/.kalibro \
 && chown :tomcat6 /var/lib/tomcat6/webapps \
 && chmod 664 -R /var/lib/tomcat6/webapps \
 && chmod +x /var/lib/tomcat6/webapps

RUN cd /root/ && wget -q https://downloads.sourceforge.net/project/kalibrometrics/KalibroService.tar.gz
RUN tar xzf /root/KalibroService.tar.gz -C "/var/lib/tomcat6/webapps" \
 --strip-components 1 "KalibroService/KalibroService.war"

ADD kalibro.settings /usr/share/tomcat6/.kalibro/kalibro.settings
ADD kalibro_test.settings /usr/share/tomcat6/.kalibro/kalibro_test.settings

ADD create_db.sh /tmp/create_db.sh
RUN service postgresql start && sleep 2 && su postgres -c /tmp/create_db.sh